

import DashboardSidebar from "@/components/DashboardSidebar/DashboardSidebar";
import DashboardHeader from "@/components/DashboardHeader/DashboardHeader";

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex ">
      {/* Sidebar */}
      <DashboardSidebar />

      {/* Main content area */}
      <div className="flex-1 flex flex-col overflow-hidden">
        {/* Header */}
        <DashboardHeader />

        {/* Page Content */}
        <main className="flex-1 overflow-y-auto p-6 bg-gray-50 dark:bg-gray-900">
          {children}
        </main>
      </div>
    </div>
  );
}


// import DashboardSidebar from "@/components/DashboardSidebar/DashboardSidebar";
// import type { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function DashboardLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <div className="flex h-screen">
//       {/* Sidebar - fixed width */}
//       <div className="w-64 bg-gray-800 text-white">
//         <DashboardSidebar />
//       </div>

//       {/* Main Content - flexible */}
//       <div className="flex-1 overflow-y-auto p-6 bg-gray-50 dark:bg-gray-900">
//         {children}
//       </div>
//     </div>
//   );
// }
